import re
from typing import Dict, List, Any

class SigmaEvaluator:
    

    BUILTIN_SIGMA_RULES = [
        {
            "id": "SIGMA-001",
            "title": "Obfuscated / Base64 Encoded PowerShell Command",
            "category": "Execution",
            "severity": "HIGH",
            "mitre_id": "T1059.001",
            "pattern": r"(?i)powershell.*(-e|-enc|-encodedcommand)\s+[a-z0-9+/=]{10,}",
            "description": "Detects execution of encoded PowerShell commands commonly used by initial access payloads."
        },
        {
            "id": "SIGMA-002",
            "title": "LSASS Memory Credential Dumping Attempt",
            "category": "Credential Access",
            "severity": "HIGH",
            "mitre_id": "T1003.001",
            "pattern": r"(?i)(sekurlsa::logonpasswords|procdump.*lsass|comsvcs.*minidump)",
            "description": "Detects LSASS process memory dumping signatures associated with Mimikatz and Procdump."
        },
        {
            "id": "SIGMA-003",
            "title": "Certutil Abuse for Remote File Download",
            "category": "Defense Evasion",
            "severity": "MEDIUM",
            "mitre_id": "T1105",
            "pattern": r"(?i)certutil.*-urlcache.*-f\s+http",
            "description": "Detects abuse of Living-off-the-Land binary Certutil to fetch external malicious payloads."
        },
        {
            "id": "SIGMA-004",
            "title": "Registry SAM/System Hive Dumping",
            "category": "Credential Access",
            "severity": "HIGH",
            "mitre_id": "T1003.002",
            "pattern": r"(?i)reg\s+save\s+hklm\\(sam|system|security)",
            "description": "Detects command-line registry exports of local SAM and SYSTEM credential hashes."
        },
        {
            "id": "SIGMA-005",
            "title": "Persistence via Local Admin Addition",
            "category": "Persistence",
            "severity": "HIGH",
            "mitre_id": "T1136.001",
            "pattern": r"(?i)net\s+localgroup\s+administrators\s+.*\s+/add",
            "description": "Detects unexpected creation or promotion of local user accounts to the Administrators group."
        },
        {
            "id": "SIGMA-006",
            "title": "Stealth Named Pipe C2 Communication",
            "category": "Command & Control",
            "severity": "HIGH",
            "mitre_id": "T1071",
            "pattern": r"(?i)(\\\\.\\pipe\\msagent_|\\\\.\\pipe\\status_)",
            "description": "Detects unusual named pipe paths generated by stealth C2 beaconing frameworks."
        },
        {
            "id": "SIGMA-007",
            "title": "WMI Event Consumer Persistence",
            "category": "Persistence",
            "severity": "MEDIUM",
            "mitre_id": "T1546.003",
            "pattern": r"(?i)(CommandLineEventConsumer|__EventFilter)",
            "description": "Detects registration of WMI event consumers for stealthy persistence."
        },
        {
            "id": "SIGMA-008",
            "title": "Volume Shadow Copy Deletion (Ransomware)",
            "category": "Impact",
            "severity": "HIGH",
            "mitre_id": "T1490",
            "pattern": r"(?i)(vssadmin.*delete.*shadows|wmic.*shadowcopy.*delete)",
            "description": "Detects deletion of system shadow copies typically executed prior to ransomware encryption."
        }
    ]

    def get_rules(self) -> List[Dict[str, Any]]:
        return self.BUILTIN_SIGMA_RULES

    def evaluate_text(self, text: str) -> List[Dict[str, Any]]:
        matches = []
        for rule in self.BUILTIN_SIGMA_RULES:
            if re.search(rule["pattern"], text):
                matches.append({
                    "rule_id": rule["id"],
                    "title": rule["title"],
                    "category": rule["category"],
                    "severity": rule["severity"],
                    "mitre_id": rule["mitre_id"],
                    "matched_sample": text[:120]
                })
        return matches
