import json
import time
from typing import Dict, List, Any

class MasterReportGenerator:

    def __init__(self, master_summary: Dict[str, Any]):
        self.summary = master_summary
        self.host_info = master_summary.get("host_info", {})

    def to_json(self) -> str:
        return json.dumps(self.summary, indent=2, default=str)

    def to_markdown(self) -> str:
        md = []
        md.append("# MASTER LURKSEC EXECUTIVE SECURITY REPORT")
        md.append(f"**Generated Date:** {time.strftime('%Y-%m-%d %H:%M:%S')}\n")
        md.append(f"- **Host System:** `{self.host_info.get('hostname', 'N/A')}` ({self.host_info.get('local_ip', '127.0.0.1')})")
        md.append(f"- **Operating System:** `{self.host_info.get('os', 'Windows 11')}`")
        
        soc = self.summary.get("soc_incidents", {})
        md.append(f"- **Total Correlated Incidents:** `{soc.get('total_incidents', 0)}`")
        md.append(f"- **Hardening Score:** `{self.summary.get('audit', {}).get('score', 100)}%`\n")

        md.append("## Correlated SOC Incident Feed")
        incidents = soc.get("incidents", [])
        if incidents:
            md.append("| Incident ID | Engine | Category | Severity | Title | Evidence |")
            md.append("| :--- | :--- | :--- | :--- | :--- | :--- |")
            for inc in incidents[:30]:
                md.append(f"| `{inc['incident_id']}` | {inc['engine']} | `{inc['category']}` | **{inc['severity']}** | {inc['title']} | `{inc.get('evidence', '')}` |")

        md.append("\n---\n*Master Security Report generated by LurkSec Suite.*")
        return "\n".join(md)

    def to_html(self) -> str:
        soc = self.summary.get("soc_incidents", {})
        incidents = soc.get("incidents", [])
        audit = self.summary.get("audit", {})
        host = self.host_info.get("hostname", "N/A")
        ip = self.host_info.get("local_ip", "127.0.0.1")
        now = time.strftime("%Y-%m-%d %H:%M:%S")

        inc_rows = ""
        for inc in incidents[:40]:
            sev_color = "#f85149" if inc.get("severity") == "HIGH" else ("#d29922" if inc.get("severity") == "MEDIUM" else "#3fb950")
            inc_rows += f"""
            <tr>
                <td><code>{inc.get('incident_id')}</code></td>
                <td><strong style="color:#58a6ff;">{inc.get('engine')}</strong></td>
                <td>{inc.get('title')}</td>
                <td><strong style="color:{sev_color};">{inc.get('severity')}</strong></td>
                <td><code>{str(inc.get('evidence', ''))[:120]}</code></td>
            </tr>
            """

        html = f"""<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>LurkSec Executive Security Audit Report - {host}</title>
    <style>
        body {{ background: #0d1117; color: #c9d1d9; font-family: 'Inter', system-ui, sans-serif; padding: 30px; margin: 0; }}
        h1 {{ color: #ffffff; font-size: 22px; border-bottom: 2px solid #30363d; padding-bottom: 10px; }}
        .summary-box {{ background: #161b22; border: 1px solid #30363d; border-radius: 8px; padding: 20px; margin-bottom: 24px; display: grid; grid-template-columns: repeat(4, 1fr); gap: 16px; }}
        .card {{ background: #0d1117; border: 1px solid #30363d; border-radius: 6px; padding: 12px 16px; }}
        .card-title {{ font-size: 11px; color: #8b949e; text-transform: uppercase; font-weight: 700; }}
        .card-value {{ font-size: 20px; font-weight: 700; color: #ffffff; margin-top: 4px; font-family: Consolas, monospace; }}
        table {{ width: 100%; border-collapse: collapse; background: #161b22; border: 1px solid #30363d; border-radius: 8px; font-size: 12px; }}
        th, td {{ padding: 12px 16px; border-bottom: 1px solid #21262d; text-align: left; }}
        th {{ background: #21262d; color: #8b949e; font-size: 11px; text-transform: uppercase; }}
        code {{ font-family: Consolas, monospace; font-size: 11px; }}
    </style>
</head>
<body>
    <h1>LurkSec Executive Security Audit Report</h1>
    <div class="summary-box">
        <div class="card"><div class="card-title">Host System</div><div class="card-value">{host}</div></div>
        <div class="card"><div class="card-title">Local IP</div><div class="card-value">{ip}</div></div>
        <div class="card"><div class="card-title">Total Incidents</div><div class="card-value" style="color:#f85149;">{soc.get('total_incidents', 0)}</div></div>
        <div class="card"><div class="card-title">Audit Score</div><div class="card-value" style="color:#3fb950;">{audit.get('score', 100)}%</div></div>
    </div>

    <h2>Correlated Security Incident Log ({len(incidents)} Incidents)</h2>
    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Engine</th>
                <th>Title</th>
                <th>Severity</th>
                <th>Evidence</th>
            </tr>
        </thead>
        <tbody>
            {inc_rows or '<tr><td colspan="5" style="color:#8b949e;">Zero active security threats. System baseline clean.</td></tr>'}
        </tbody>
    </table>
    <p style="margin-top:24px;font-size:11px;color:#8b949e;">Generated: {now} by LurkSec Unified Security Suite.</p>
</body>
</html>"""
        return html

    def generate_json(self) -> str:
        return self.to_json()

    def generate_markdown(self) -> str:
        return self.to_markdown()

    def generate_html(self) -> str:
        return self.to_html()
