import json
import time
from typing import Dict, List, Any

class MasterReportGenerator:
    """
    Generates Master Executive LurkSec Security Operations Reports.
    Matches the Minimalist Charcoal Console Theme.
    """

    def __init__(self, master_summary: Dict[str, Any]):
        self.summary = master_summary
        self.host_info = master_summary.get("host_info", {})

    def to_json(self) -> str:
        return json.dumps(self.summary, indent=2, default=str)

    def to_markdown(self) -> str:
        md = []
        md.append("# MASTER LURKSEC EXECUTIVE SECURITY REPORT")
        md.append(f"**Generated Date:** {time.strftime('%Y-%m-%d %H:%M:%S')}\n")
        md.append(f"- **Host System:** `{self.host_info.get('hostname', 'N/A')}` ({self.host_info.get('local_ip', '127.0.0.1')})")
        md.append(f"- **Operating System:** `{self.host_info.get('os', 'Windows 11')}`")
        
        soc = self.summary.get("soc_incidents", {})
        md.append(f"- **Total Correlated Incidents:** `{soc.get('total_incidents', 0)}`")
        md.append(f"- **Hardening Score:** `{self.summary.get('audit', {}).get('score', 100)}%`\n")

        md.append("## Correlated SOC Incident Feed")
        incidents = soc.get("incidents", [])
        if incidents:
            md.append("| Incident ID | Engine | Category | Severity | Title | Evidence |")
            md.append("| :--- | :--- | :--- | :--- | :--- | :--- |")
            for inc in incidents[:30]:
                md.append(f"| `{inc['incident_id']}` | {inc['engine']} | `{inc['category']}` | **{inc['severity']}** | {inc['title']} | `{inc.get('evidence', '')}` |")

        md.append("\n---\n*Master Security Report generated by LurkSec Suite Command Center.*")
        return "\n".join(md)

    def to_html(self) -> str:
        soc = self.summary.get("soc_incidents", {})
        incidents = soc.get("incidents", [])
        audit = self.summary.get("audit", {})

        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Master LurkSec Executive Security Report</title>
    <link href="https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@400;500;600;700&display=swap" rel="stylesheet">
    <style>
        * {{ box-sizing: border-box; }}
        body {{ font-family: 'JetBrains Mono', 'Consolas', monospace; background: #0d1117; color: #c9d1d9; font-size: 12px; margin: 0; padding: 40px; line-height: 1.5; }}
        .container {{ max-width: 1000px; margin: 0 auto; background: #161b22; padding: 32px; border: 1px solid #30363d; border-radius: 4px; overflow: hidden; }}
        .header-title {{ font-size: 18px; font-weight: 700; color: #ffffff; letter-spacing: 0.5px; margin: 0 0 4px 0; }}
        .header-sub {{ font-size: 11px; color: #8b949e; margin-bottom: 24px; border-bottom: 1px solid #30363d; padding-bottom: 12px; display: flex; justify-content: space-between; }}
        h2 {{ font-size: 14px; color: #58a6ff; margin-top: 28px; margin-bottom: 12px; border-bottom: 1px solid #30363d; padding-bottom: 6px; font-weight: 600; }}
        table {{ width: 100%; border-collapse: collapse; margin-top: 12px; background: #0d1117; border: 1px solid #30363d; table-layout: fixed; }}
        th, td {{ padding: 8px 12px; text-align: left; border-bottom: 1px solid #30363d; font-size: 11px; word-wrap: break-word; word-break: break-word; overflow-wrap: break-word; }}
        th {{ background: #161b22; color: #8b949e; font-size: 10px; text-transform: uppercase; letter-spacing: 0.5px; font-weight: 600; }}
        tr:nth-child(even) {{ background: #0d1117; }}
        tr:hover {{ background: #1f242c; }}
        code {{ background: #21262d; color: #58a6ff; padding: 2px 6px; border-radius: 2px; font-size: 11px; word-break: break-all; }}
        .alert-tag {{ color: #f85149; font-weight: bold; }}
        .pass-tag {{ color: #3fb950; font-weight: bold; }}
        .metric-grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 12px; margin: 20px 0; }}
        .metric-card {{ background: #0d1117; padding: 14px; border: 1px solid #30363d; border-radius: 3px; }}
        .metric-label {{ font-size: 10px; color: #8b949e; font-weight: bold; letter-spacing: 0.5px; }}
        .metric-value {{ font-size: 20px; font-weight: bold; color: #ffffff; margin-top: 4px; }}
        .col-id {{ width: 160px; }}
        .col-eng {{ width: 120px; }}
        .col-cat {{ width: 130px; }}
        .col-sev {{ width: 80px; }}
    </style>
</head>
<body>
    <div class="container">
        <div class="header-title">MASTER LURKSEC EXECUTIVE SECURITY REPORT</div>
        <div class="header-sub">
            <span>AUDIT GENERATED: {time.strftime('%Y-%m-%d %H:%M:%S')}</span>
            <span>HOST: {self.host_info.get('hostname', 'Localhost')} ({self.host_info.get('local_ip', '127.0.0.1')})</span>
        </div>

        <div class="metric-grid">
            <div class="metric-card"><div class="metric-label">TOTAL INCIDENTS</div><div class="metric-value">{soc.get('total_incidents', 0)}</div></div>
            <div class="metric-card"><div class="metric-label">HARDENING SCORE</div><div class="metric-value" style="color:#3fb950;">{audit.get('score', 100)}%</div></div>
            <div class="metric-card"><div class="metric-label">HIGH SEVERITY</div><div class="metric-value" style="color:#f85149;">{soc.get('severity_counts', {}).get('HIGH', 0)}</div></div>
            <div class="metric-card"><div class="metric-label">SYSTEM OS</div><div class="metric-value" style="font-size:14px;margin-top:8px;">{self.host_info.get('os', 'Windows 11')}</div></div>
        </div>

        <h2>Correlated Incident Command Feed</h2>
        <table>
            <thead>
                <tr><th class="col-id">Incident ID</th><th class="col-eng">Engine</th><th class="col-cat">Category</th><th class="col-sev">Severity</th><th>Title</th><th>Evidence</th></tr>
            </thead>
            <tbody>
                {''.join([f"<tr><td><code>{inc['incident_id']}</code></td><td>{inc['engine']}</td><td>{inc['category']}</td><td><span class='alert-tag'>{inc['severity']}</span></td><td>{inc['title']}</td><td><code>{inc.get('evidence', '')}</code></td></tr>" for inc in incidents[:30]])}
            </tbody>
        </table>
    </div>
</body>
</html>"""
        return html
