import json
import time
from typing import Dict, List, Any

class MasterReportGenerator:
    

    def __init__(self, master_summary: Dict[str, Any]):
        self.summary = master_summary
        self.host_info = master_summary.get("host_info", {})

    def to_json(self) -> str:
        return json.dumps(self.summary, indent=2, default=str)

    def to_markdown(self) -> str:
        md = []
        md.append("# MASTER LURKSEC EXECUTIVE SECURITY REPORT")
        md.append(f"**Generated Date:** {time.strftime('%Y-%m-%d %H:%M:%S')}\n")
        md.append(f"- **Host System:** `{self.host_info.get('hostname', 'N/A')}` ({self.host_info.get('local_ip', '127.0.0.1')})")
        md.append(f"- **Operating System:** `{self.host_info.get('os', 'Windows 11')}`")
        
        soc = self.summary.get("soc_incidents", {})
        md.append(f"- **Total Correlated Incidents:** `{soc.get('total_incidents', 0)}`")
        md.append(f"- **Hardening Score:** `{self.summary.get('audit', {}).get('score', 100)}%`\n")

        md.append("## Correlated SOC Incident Feed")
        incidents = soc.get("incidents", [])
        if incidents:
            md.append("| Incident ID | Engine | Category | Severity | Title | Evidence |")
            md.append("| :--- | :--- | :--- | :--- | :--- | :--- |")
            for inc in incidents[:30]:
                md.append(f"| `{inc['incident_id']}` | {inc['engine']} | `{inc['category']}` | **{inc['severity']}** | {inc['title']} | `{inc.get('evidence', '')}` |")

        md.append("\n---\n*Master Security Report generated by LurkSec Suite Command Center.*")
        return "\n".join(md)

    def to_html(self) -> str:
        soc = self.summary.get("soc_incidents", {})
        incidents = soc.get("incidents", [])
        audit = self.summary.get("audit", {})

        html = f
        return html

    def generate_json(self) -> str:
        return self.to_json()

    def generate_markdown(self) -> str:
        return self.to_markdown()

    def generate_html(self) -> str:
        return self.to_html()
